[build]
  command = "pnpm build"
  publish = ".next"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client","bcryptjs"]
  included_files = ["node_modules/.prisma/client/**","prisma/schema.prisma"]