import type { Metadata } from 'next';
import { Geologica } from 'next/font/google';
import './globals.css';

import Script from 'next/script';
import ThemeHydrator from './_theme/ThemeHydrator';

const geologica = Geologica({
  variable: '--font-geologica',
  subsets: ['latin', 'cyrillic'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="uk" suppressHydrationWarning>
      <head>
        <Script src="/theme-init.js" strategy="beforeInteractive" />
      </head>
      <body className={`${geologica.variable} antialiased`}>
        <ThemeHydrator />
        {children}
      </body>
    </html>
  );
}
